add Notify
qbcore-framework/qb-phone pull request #103
Opened 2021-09-15 10:06 UTC by evanillaa

2021-09-21 00:56 UTC, phumberdroz requested changes

2021-09-21 00:56 UTC, phumberdroz commented on client/main.lua
> +	QBCore.Functions.Notify("The phone number has been received", "success")
```suggestion
        QBCore.Functions.Notify("The phone number has been received", "success")
```

2021-09-27 17:24 UTC, tomasalves8 commented
@evanillaa Can you make the changes above?

2021-09-27 18:27 UTC, tomasalves8 approved these changes

2021-11-03 06:51 UTC, closed without merging