Add server ID to phone
qbcore-framework/qb-phone pull request #165
Opened 2021-11-14 05:02 UTC by Bigbearbeasttv

![image](https://user-images.githubusercontent.com/87631565/141668270-a7c66643-21d8-49c3-91c7-ad42e08f5390.png)

2021-11-14 09:52 UTC, jnccloud requested changes
The player's ID should already be provided in app.js if you access QB.Phone.Data.PlayerData.source in app.js which eliminates the need for adding a new output via any of the .lua scripts. I also recommend using the same styles as the clock because Times New Roman just isn't it in 2021.

2021-11-14 09:52 UTC, jnccloud commented on client/main.lua
> +            serverid = GetPlayerServerId(PlayerId())
The server ID should already be in PlayerData

2021-11-14 09:52 UTC, jnccloud commented on html/index.html
> +                        <i class="fas fa-hashtag" style="padding-right: 10px;" id="phone-serverid" data-toggle="tooltip" data-placement="left" title="Server ID"></i>
Should definitely look at a better way to apply styles here, look at the clock code inside the phone for more details.

2021-11-14 09:52 UTC, jnccloud commented on html/js/app.js
> +    $("#phone-serverid").html("<span style='font-size: 1.3vh; font-weight:bold;'>" + data.serverid + "</span>");
Adding attributes like style should be handled in CSS not inline...

2021-11-14 09:52 UTC, jnccloud commented on html/js/app.js
> +    console.log("Phone succesfully loaded!");
I think this was removed in the most recent updates? It's a debug print.. doesn't really serve a purpose to anyone.

2021-11-16 04:34 UTC, Bigbearbeasttv commented
Now conflicts with new reskin

2021-11-16 05:04 UTC, closed without merging