Click on the phone number and Serial Number to add to clipboard in settings app
qbcore-framework/qb-phone pull request #394
Opened 2024-05-04 17:50 UTC by mrdiamonddirt

## Description
Phone Number and Serial Number copied to clipboard when clicked in settings page
![image](https://github.com/qbcore-framework/qb-phone/assets/25391741/b1e2f56f-8164-48ca-b42e-9bf2565d9b55)

## Checklist

- [x] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2024-05-04 17:54 UTC, gononono64 commented
Looks solid. This should be added because often, people want to send or use their in-game phone number outside of fivem.  Ill test it in a few

2024-06-24 21:47 UTC, Z3rio requested changes
I dont really think we should be importing yet another library just for something which can be done in 2-3 lines of standard JS, aka setting the clipboard.

QB-Phone is already bloated enough as it is...

2024-06-24 21:50 UTC, gononono64 commented
> I dont really think we should be importing yet another library just for something which can be done in 2-3 lines of standard JS, aka setting the clipboard.
> 
> QB-Phone is already bloated enough as it is...

Imo copy to clipboard should be part of core

2024-06-24 21:52 UTC, Z3rio commented
> > I dont really think we should be importing yet another library just for something which can be done in 2-3 lines of standard JS, aka setting the clipboard.
> > QB-Phone is already bloated enough as it is...
> 
> Imo copy to clipboard should be part of core

Apart of qb-core? Yeah, perhaps, would be nice when trying to set the clipboard from lua.

Wouldnt really be useable/ideal in this situation even if it was in qb-core though.
As you'd have to go from the UI, to the clientside of qb-phone, then to the clientside of qb-core, then to the UI of qb-core.

Much better to just write those 2-3 lines of JS in qb-phone in this situation.

2024-06-24 23:21 UTC, mrdiamonddirt commented
Absolutely 👍 didn't spend too much time with it but I would've thought i'd tried it without a library and thought it didn't work for some reason so probably did that naturally I thought I could do it with native js but not looked at this really since posting was just a quick implementation that worked

2024-06-24 23:39 UTC, mrdiamonddirt commented
I might pull it down and have a look again and see why I didn't use the clipboard I'm sure I remember trying it, but someone could always pull it down remove the package add the 2-3 lines of js and that I maybe missed and create the pr again and comment on this to say it's outdated because of pr # I don't have or use qb-phone and am not a "qb-core developer" obviously this isn't top of list of things for me todo 😀 but I appreciate the comments and the response @Z3rio and any constructive criticism is always appreciated

2024-06-25 00:48 UTC, Z3rio commented
> I might pull it down and have a look again and see why I didn't use the clipboard I'm sure I remember trying it, but someone could always pull it down remove the package add the 2-3 lines of js and that I maybe missed and create the pr again and comment on this to say it's outdated because of pr # I don't have or use qb-phone and am not a "qb-core developer" obviously this isn't top of list of things for me todo 😀 but I appreciate the comments and the response @Z3rio and any constructive criticism is always appreciated

Yeah, well, if qb-core actually cared about PRs and merged them, I'd 110% do that.
But I already have 6 PRs of my own waiting on being merged lmfao

2024-06-25 07:06 UTC, mrdiamonddirt commented
I completely get that buddy I also like to not have a load of outstanding pr's, so I keep them few and fairly minimal my argument for this way could be yeah it adds 25 lines and a libary but it is a very minimal libary and makes re-use of the copy function I implemented to be very easily re-used elsewhere, yes it may able to be done more minimally, but I honestly like this implementation,😂🤣 and I'm not flaming your comments at all @Z3rio they are obviously valid

2024-07-08 22:27 UTC, ChristianBDev requested changes
Can you add this to the settings.js, line 38 
```
$(document).on(
    "click",
    "#phoneNumberSelect, #serialNumberSelect",
    function (e) {
        // Get the title of the clicked element
        var title = "";
        if ($(this).attr("id") == "phoneNumberSelect") {
            title = "Phone Number";
        } else {
            title = "Serial Number";
        }

        // get the result id of myPhoneNumber or mySerialNumber
        var textToCopy =
            $(this).attr("id") == "phoneNumberSelect"
                ? $("#myPhoneNumber").text()
                : $("#mySerialNumber").text();

        // Copying the text to clipboard using Clipboard.js
        var clipboard = new ClipboardJS(this, {
            text: function () {
                QB.Phone.Notifications.Add("fas fa-phone", "Copied " + title + "!", textToCopy);
                return textToCopy;
            },
        });
    }
);
``` 
and delete the line on 1135 
`<script src="./js/copyclipboard.js"></script>`

2024-07-09 16:52 UTC, ChristianBDev requested changes
Add this to the settings.js instead ```
$(document).on(
    "click",
    "#phoneNumberSelect, #serialNumberSelect",
    function (e) {
        // Get the title of the clicked element
        var title = "";
        if ($(this).attr("id") == "phoneNumberSelect") {
            title = "Phone Number";
        } else {
            title = "Serial Number";
        }

        // get the result id of myPhoneNumber or mySerialNumber
        var textToCopy =
            $(this).attr("id") == "phoneNumberSelect"
                ? $("#myPhoneNumber").text()
                : $("#mySerialNumber").text();

        // Copying the text to clipboard using Clipboard.js
        var clipboard = new ClipboardJS(this, {
            text: function () {
                QB.Phone.Notifications.Add("fas fa-phone", "Copied " + title + "!", textToCopy);
                return textToCopy;
            },
        });
    }
);```

2024-07-09 16:52 UTC, ChristianBDev commented on html/index.html
> +        <script src="./js/copyclipboard.js"></script>
Remove this

2024-07-09 16:52 UTC, ChristianBDev commented on html/js/copyclipboard.js
> +);
remove this

2024-07-10 18:50 UTC, ChristianBDev approved these changes
Tested, LGTM

2024-07-25 19:36 UTC, merged